CREATE DATABASE usermanagement;

CREATE TABLE usermanagement.roles (
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    role VARCHAR(15) UNIQUE NOT NULL,
	permissions VARCHAR(10) NOT NULL
);

INSERT INTO usermanagement.roles (role, permissions) VALUES ('Administrator', 'read-write');
INSERT INTO usermanagement.roles (role, permissions) VALUES ('Moderator', 'read-only');
INSERT INTO usermanagement.roles (role, permissions) VALUES ('User', 'no-access');

CREATE TABLE usermanagement.accounts (
	account_id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	permissions_id INT DEFAULT 3,
	username VARCHAR(50) NOT NULL,
	password VARCHAR(50) NOT NULL,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL,
	phone VARCHAR(50) NOT NULL,
	comments TEXT,
	date_created DATE NOT NULL,
	status VARCHAR(10) NOT NULL DEFAULT 'active',
	FOREIGN KEY(permissions_id) REFERENCES roles(id)
);

INSERT INTO usermanagement.accounts (permissions_id, username, password, first_name, last_name, email, phone, comments, date_created, status) VALUES (1, 'admin', 'password', 'admin', 'admin', 'administrator@admin.com', '+62 316 527 3759', 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', '2021-02-19', 'active');
INSERT INTO usermanagement.accounts (permissions_id, username, password, first_name, last_name, email, phone, comments, date_created, status) VALUES (3, 'lwilprecht0', 'zsExtyU9lW', 'Leeanne', 'Wilprecht', 'lwilprecht0@barnesandnoble.com', '+62 316 527 3759', 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', '2021-02-19', 'active');
INSERT INTO usermanagement.accounts (permissions_id, username, password, first_name, last_name, email, phone, comments, date_created, status) VALUES (3, 'ubreem1', 'srvVwYpaqfm', 'Ulises', 'Breem', 'ubreem1@yellowbook.com', '+86 276 371 5950', 'In quis justo.', '2021-06-09', 'active');
INSERT INTO usermanagement.accounts (permissions_id, username, password, first_name, last_name, email, phone, comments, date_created, status) VALUES (3, 'bcoppens2', 'CQfOPsQfNpGf', 'Benny', 'Coppens', 'bcoppens2@lulu.com', '+54 624 207 1328', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo.', '2021-04-13', 'active');
INSERT INTO usermanagement.accounts (permissions_id, username, password, first_name, last_name, email, phone, comments, date_created, status) VALUES (3, 'lfazan3', '4l15qE', 'Lilla', 'Fazan', 'lfazan3@godaddy.com', '+42 295 176 7427', 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', '2021-12-27', 'active');
INSERT INTO usermanagement.accounts (permissions_id, username, password, first_name, last_name, email, phone, comments, date_created, status) VALUES (3, 'cpigrome4', 'lMpEpyO3sp', 'Cindra', 'Pigrome', 'cpigrome4@economist.com', '+63 948 491 6803', 'Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', '2021-11-04', 'active');
INSERT INTO usermanagement.accounts (permissions_id, username, password, first_name, last_name, email, phone, comments, date_created, status) VALUES (3, 'abinestead5', '2BX6VajyR', 'Agretha', 'Binestead', 'abinestead5@123-reg.co.uk', '+31 748 102 5695', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', '2021-06-06', 'active');
INSERT INTO usermanagement.accounts (permissions_id, username, password, first_name, last_name, email, phone, comments, date_created, status) VALUES (3, 'lhackin6', '0p7Zbj2LDu', 'Luci', 'Hackin', 'lhackin6@slashdot.org', '+86 507 347 6114', 'Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.', '2021-05-20', 'active');
INSERT INTO usermanagement.accounts (permissions_id, username, password, first_name, last_name, email, phone, comments, date_created, status) VALUES (3, 'cbranwhite7', 'gifq2f5Vx', 'Chuck', 'Branwhite', 'cbranwhite7@tripod.com', '+35 722 675 6485', 'Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', '2021-11-21', 'active');
INSERT INTO usermanagement.accounts (permissions_id, username, password, first_name, last_name, email, phone, comments, date_created, status) VALUES (3, 'pcayet8', 'aPKviFAxb4H', 'Philip', 'Cayet', 'pcayet8@earthlink.net', '+31 291 675 3066', 'Curabitur gravida nisi at nibh.', '2021-08-12', 'active');
INSERT INTO usermanagement.accounts (permissions_id, username, password, first_name, last_name, email, phone, comments, date_created, status) VALUES (3, 'etyas9', '6UC4djb', 'Everett', 'Tyas', 'etyas9@harvard.edu', '+62 580 510 5732', 'Donec quis orci eget orci vehicula condimentum.', '2021-05-16', 'active');
INSERT INTO usermanagement.accounts (permissions_id, username, password, first_name, last_name, email, phone, comments, date_created, status) VALUES (3, 'tclemersona', 'TlrphuR', 'Trueman', 'Clemerson', 'tclemersona@nps.gov', '+86 586 167 1833', 'Phasellus id sapien in sapien iaculis congue.', '2021-11-27', 'active');
INSERT INTO usermanagement.accounts (permissions_id, username, password, first_name, last_name, email, phone, comments, date_created, status) VALUES (3, 'amayhoub', '4t0bsV', 'Alexis', 'Mayhou', 'amayhoub@nydailynews.com', '+76 903 735 7861', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.', '2021-12-26', 'active');
INSERT INTO usermanagement.accounts (permissions_id, username, password, first_name, last_name, email, phone, comments, date_created, status) VALUES (3, 'lgaulc', 'Qw9TW1GXHVd9', 'Lida', 'Gaul', 'lgaulc@mit.edu', '+55 263 641 0961', 'Phasellus sit amet erat. Nulla tempus.', '2021-06-16', 'active');
INSERT INTO usermanagement.accounts (permissions_id, username, password, first_name, last_name, email, phone, comments, date_created, status) VALUES (3, 'byakuntsovd', '7oi3MfB', 'Broderick', 'Yakuntsov', 'byakuntsovd@theglobeandmail.com', '+86 656 266 9285', 'Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.', '2021-10-12', 'active');
INSERT INTO usermanagement.accounts (permissions_id, username, password, first_name, last_name, email, phone, comments, date_created, status) VALUES (3, 'siacovuzzie', 'S1UCSQ', 'Shelbi', 'Iacovuzzi', 'siacovuzzie@salon.com', '+52 678 440 8010', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', '2021-06-09', 'active');
INSERT INTO usermanagement.accounts (permissions_id, username, password, first_name, last_name, email, phone, comments, date_created, status) VALUES (3, 'dbesemerf', 'QJ0bc9pa', 'Delaney', 'Besemer', 'dbesemerf@nydailynews.com', '+86 142 373 6875', 'Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.', '2021-06-29', 'active');
INSERT INTO usermanagement.accounts (permissions_id, username, password, first_name, last_name, email, phone, comments, date_created, status) VALUES (3, 'bbraisherg', 'mHC8BfIl8FVI', 'Buck', 'Braisher', 'bbraisherg@bloomberg.com', '+23 544 772 6087', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.', '2021-03-17', 'active');
INSERT INTO usermanagement.accounts (permissions_id, username, password, first_name, last_name, email, phone, comments, date_created, status) VALUES (3, 'fpuckrinh', 'xmuP2fe7', 'Flss', 'Puckrin', 'fpuckrinh@china.com.cn', '+64 818 820 9519', 'Proin interdum mauris non ligula pellentesque ultrices.', '2021-03-11', 'active');
INSERT INTO usermanagement.accounts (permissions_id, username, password, first_name, last_name, email, phone, comments, date_created, status) VALUES (3, 'ksabatinii', 'EWKyZb0Tc7', 'Kimbra', 'Sabatini', 'ksabatinii@unblog.fr', '+62 929 192 5984', 'Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '2021-03-06', 'active');
INSERT INTO usermanagement.accounts (permissions_id, username, password, first_name, last_name, email, phone, comments, date_created, status) VALUES (3, 'jloughreyj', '3rrIsw', 'Jean', 'Loughrey', 'jloughreyj@businessinsider.com', '+27 743 224 0388', 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', '2021-09-09', 'active');
INSERT INTO usermanagement.accounts (permissions_id, username, password, first_name, last_name, email, phone, comments, date_created, status) VALUES (3, 'afeaviourk', '9gIlwYCEFsa', 'Aloise', 'Feaviour', 'afeaviourk@4shared.com', '+62 615 609 1877', 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.', '2021-10-16', 'active');
INSERT INTO usermanagement.accounts (permissions_id, username, password, first_name, last_name, email, phone, comments, date_created, status) VALUES (3, 'cternentl', 'gI7fFpqyNQ', 'Camile', 'Ternent', 'cternentl@stanford.edu', '+36 503 243 7869', 'Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', '2021-04-09', 'active');
INSERT INTO usermanagement.accounts (permissions_id, username, password, first_name, last_name, email, phone, comments, date_created, status) VALUES (3, 'owhottonm', 'oYOpld', 'Olivia', 'Whotton', 'owhottonm@house.gov', '+62 614 555 5298', 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', '2021-09-14', 'active');
INSERT INTO usermanagement.accounts (permissions_id, username, password, first_name, last_name, email, phone, comments, date_created, status) VALUES (3, 'ekollaschn', 'TY3AFejRrj7H', 'Elia', 'Kollasch', 'ekollaschn@npr.org', '+62 161 422 0516', 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', '2021-03-29', 'active');
INSERT INTO usermanagement.accounts (permissions_id, username, password, first_name, last_name, email, phone, comments, date_created, status) VALUES (3, 'scrabbeo', 'anoelb', 'Sibley', 'Crabbe', 'scrabbeo@bloglines.com', '+77 880 186 6723', 'Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '2021-10-19', 'active');
INSERT INTO usermanagement.accounts (permissions_id, username, password, first_name, last_name, email, phone, comments, date_created, status) VALUES (3, 'hhoulisonp', 'oe58qPblqZ', 'Hewe', 'Houlison', 'hhoulisonp@slideshare.net', '+86 390 454 6972', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', '2021-05-09', 'active');
INSERT INTO usermanagement.accounts (permissions_id, username, password, first_name, last_name, email, phone, comments, date_created, status) VALUES (3, 'elesorq', '3l0FX2qYzbxO', 'Eleonore', 'Lesor', 'elesorq@cornell.edu', '+63 640 253 9774', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2021-07-07', 'active');
INSERT INTO usermanagement.accounts (permissions_id, username, password, first_name, last_name, email, phone, comments, date_created, status) VALUES (3, 'dfomichyovr', 'mfyWnNPdVuc', 'Darlleen', 'Fomichyov', 'dfomichyovr@woothemes.com', '+51 130 765 4360', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', '2021-02-12', 'active');
INSERT INTO usermanagement.accounts (permissions_id, username, password, first_name, last_name, email, phone, comments, date_created, status) VALUES (3, 'cmcgreals', 'K4218B6sZsu', 'Chantal', 'McGreal', 'cmcgreals@plala.or.jp', '+57 769 358 8286', 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.', '2021-02-26', 'active');
INSERT INTO usermanagement.accounts (permissions_id, username, password, first_name, last_name, email, phone, comments, date_created, status) VALUES (3, 'dyedyt', 'IeISBM', 'Darn', 'Yedy', 'dyedyt@cornell.edu', '+66 771 714 6082', 'Vivamus tortor. Duis mattis egestas metus.', '2021-05-24', 'active');